### ISSUE TITLE
spark api

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/snappydata#296] opened 2016-07-05 01:42 UTC
Correct me if I am wrong, from snappydata docs, it says that I should be able to access snappydata from external spark deployment by using snappycontext, am I correct? So can I do the following  in a spark-shell -

val conf = new org.apache.spark.SparkConf()
            .setAppName("mySnappyApp")
            .setMaster("local[*]")
            .set("jobserver.enabled", "true")
            .set("snappydata.store.locators", "localhost:10334")
            .set("spark.ui.port", "4042")
            .set("spark.driver.extraLibraryPath", "/home/thbeh/snappydata-0.4.0-PREVIEW-bin/lib")
            .set("spark.driver.allowMultipleContexts","true")

val sc = new org.apache.spark.SparkContext(conf)
val sqlContext = new org.apache.spark.sql.SnappyContext(sc)
val airline = sqlContext.table("airline").show

.....but I got this error......

_conf: org.apache.spark.SparkConf = org.apache.spark.SparkConf@59b778dc
sc: org.apache.spark.SparkContext = org.apache.spark.SparkContext@6f25a644
<console>:31: error: type SnappyContext is not a member of package org.apache.spark.sql
         val sqlContext = new org.apache.spark.sql.SnappyContext(sc)_

I trying to use spark interpreter in Zeppelin. Please advice

**Comment by rishitesh** [comment] 2016-07-05 05:38
As far as I know Zepelin creates a SparkContext implicitly. You can put Snappy libraries in spark dependency folder in Zeppelin.

**Comment by SachinJanani** [comment] 2016-07-05 06:03
@thbeh  If you are using zeppelin 0.5.6 then replace  ` zeppelin-0.5.6-incubating-bin-all/interpreter/spark/dep/zeppelin-spark-dependencies-0.5.6-incubating.jar ` with `snappydata-assembly_2.10-0.4.0-PREVIEW-hadoop2.4.1.jar` this is because zeppelin is embedded with Spark 1.5 and snappydata-0.4 supports spark 1.6.Please let me know if you face any issues

**Comment by thbeh** [comment] 2016-07-05 07:36
Hi, I am using v0.6.0 of Zeppelin, do I need  to do the same?

Regards
Beh

**Comment by SachinJanani** [comment] 2016-07-05 09:04
For zeppelin 0.6 you have to only copy ` snappydata-assembly_2.10-0.4.0-PREVIEW-hadoop2.4.1.jar` in `<ZEPPELIN_HOME>/interpreter/spark/dep/`

**Comment by thbeh** [comment] 2016-07-05 21:15
So I copied jar as Sachin instructed and doesn't make sense, what did I
missed?

[image: Inline image 2]

**Comment by hbhanawat** [comment] 2016-07-05 22:51
@thbeh Can't see the attachment.

**Comment by thbeh** [comment] 2016-07-05 23:15
Re sent image as attachment

[image: Inline image 1]

**Comment by hbhanawat** [comment] 2016-07-05 23:18
@thbeh Still can't see it. Looked at the github page as well but is not visible there too. https://github.com/SnappyDataInc/snappydata/issues/296

**Comment by thbeh** [comment] 2016-07-05 23:29
![98b0399d-9e72-49e6-a5b3-df3531c64548](https://cloud.githubusercontent.com/assets/7357830/16603020/cf2c9edc-436c-11e6-9d51-1306fac341f7.png)

**Comment by thbeh** [comment] 2016-07-05 23:42
You should be able to see it now.

One very funny thing is that I have to set 'zeppelin.spark.useHiveContext
to false' before I could see snappy store. But %sql still complaining about
table does not exist.

**Comment by hbhanawat** [comment] 2016-07-06 02:36
What is happening here is that you have registered airlines table as a temp table in SnappyContext, which is a specialized SQLContext. and you are querying it using %sql  which internally uses a SQLContext. Temp tables are not visible across contexts. 

You can do two things here. 

1. You can make your query run by firing sqlContext.sql("your query here"). sqlContext is the SnappyContext that you have created.
2. You can use zeppelin server from our our forked Zeppelin repo so that you don't have to run the query using sqlContext.sql. You can then use %snappy-sql to fire the queries directly.

With 0.6 release of zeppellin they are allowing better integration for interpreters. We are working on adding an interpreter for Snappy.

**Comment by thbeh** [comment] 2016-07-06 02:36
I reverted back to 0.5.6 but looks the same. I have attached a snapshot, in the same notebook, one datasource  from snappydata and another from csv. The csv converted to DF->TempTable works fine but not the DF from snappy - 

![zeppelin_0 5 6](https://cloud.githubusercontent.com/assets/7357830/16605861/02ed010c-4387-11e6-943c-cb6b3b0174fc.PNG)

**Comment by thbeh** [comment] 2016-07-06 03:10
I don't see a zeppelin repo in snappydatainc's github?

**Comment by jramnara** [comment] 2016-07-06 04:48
Same problem as reported by Hemant. 'temp' is scoped by the SnappyContext and 'Auction' is scoped by the spark context you created. 

We haven't yet the Snappydata Zeppelin interpreter public, yet. 
@rishitesh, @SachinJanani can you guys make the latest branch with the Zeppelin interpreter and support for 0.6 zeppelin accessible? in fact, make the binary distribution for this branch available. I think that will resolve all issues reported here. 

@thbeh can simply use '%snappy-sql' for his second para.

**Comment by thbeh** [comment] 2016-07-06 04:57
Great, hopefully I can get my hands on it soon. Maybe someone can point me
to the repo I could compile from source as I did for Zeppelin 0.6.0. Thanks

**Comment by SachinJanani** [comment] 2016-07-06 09:02
@thbeh We are about to create the binaries for the Zeppelin with snappydata interpreter but for now you can use the attached snappydata interpreter.Following are the steps that you will need in order to install snappydata interpreter in zeppelin 0.6:
1) Download attached `snappydata-interpreter.tar.gz`
2) Extract `snappydata-interpreter.tar.gz` and copy `snappydatasql` directory from `snappydata-interpreter` in `<ZEPPELIN_HOME>/interpreter/`
3) Copy `zeppelin-site.xml` from extracted `snappydata-interpreter` to `<ZEPPELIN_HOME>/conf/`
4) Copy `snappydata-assembly_2.10-0.4.0-PREVIEW-hadoop2.4.1.jar` to `<ZEPPELIN_HOME>/interpreter/snappydatasql` directory
5) Restart zeppelin daemon
6) Verify whether snappydatasql interpreter appears in the interpreter list
[snappydata-interpreter.tar.gz](https://github.com/SnappyDataInc/snappydata/files/349420/snappydata-interpreter.tar.gz)

7) Now you can use snappydatasql interpreter using %snappydatasql 

Please let me know if you face any issues

**Comment by thbeh** [comment] 2016-07-06 23:05
the interpreter does not seem to work with my sourced compile of 0.6.0 and
coincidentally Zeppelin 0.6.0 was released to day. Downloaded that and re
copy snappydata intepreter to zeppellin and it works lie a charm.

Another thing I notice was that when a query is running and then cancelled,
snappydata server kill itself.

**Comment by SachinJanani** [comment] 2016-07-07 03:36
@thbeh  Good to hear that you are able to use interpreter.Cancelling the query should not affect the Snappydata server as this interpreter is simply a client to snappydata server. I tried to reproduce the issue that you mentioned by canceling the running query but was not able to reproduce it.
Can you please let us know the detailed steps to reproduce it

**Comment by thbeh** [comment] 2016-07-07 07:13
I am trying to produce it as well. Will update when I get the issue again.

**Comment by thbeh** [comment] 2016-07-07 21:10
So now that the interpreter looks good, how does snappydata looks like on a
mesos architecture?

**Comment by jramnara** [comment] 2016-07-07 23:52
Snappydata supports mesos when used in the split cluster mode. i.e. the
spark compute nodes are isolated from the data server nodes. The data
server nodes themselves are long running (they host data in memory) and do
not yet support mesos.

Dynamic resource management through mesos/yarn would make more sense when
running compute heavy tasks like map-reduce, anyway. What are you trying to
solve?

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by thbeh** [comment] 2016-07-08 00:04
I am trying to build a lambda architecture on top of mesos, having
snappydata as the speed layer (i think that is what snappydata is built
for) but not sure whether it make sense to do that or have a separate
cluster (maybe 3 nodes) for snappydata cluster that allows user to connect
from zeppelin.

Any thoughts?

**Comment by jramnara** [comment] 2016-07-08 00:29
I am no mesos expert but delegating to a resource manager makes a lot of
sense when workload determines the resources required and having the
cluster/resource manager allocate these on demand.
But, if you think about snappydata (or any other in-memory database for
that matter) you cannot really do this. We provision and potentially manage
large quantities of data in memory for a long period. You would lose the
value if you keep provisioning and releasing the memory (which a dynamic
resource manager is built to do).

That being said, mesos would make sense for you to manage your entire data
center (or a subset) as a farm of resources and being fully abstracted away
from knowing the nodes used for snappydata. Is this your motivation for
mesos?
I suppose, there is nothing preventing you to launch snappy using mesos
with some static provisioning policy?

When you say "speed layer" you would use snappy for both stream processing
as well as a operational in-memory db?

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by thbeh** [comment] 2016-07-08 00:52
Jags,

I think I would look at 2 scenario -

1. Long serving - conventional olap analytics
2. Ad hoc short lived requirements for ML tasks

Please refer below for my comments.

Thanks

Regards
Beh

**Comment by jramnara** [comment] 2016-07-08 01:05
thanks. thoughts below ...


> > I am no mesos expert but delegating to a resource manager makes a lot of
> > sense when workload determines the resources required and having the
> > cluster/resource manager allocate these on demand.
> > But, if you think about snappydata (or any other in-memory database for
> > that matter) you cannot really do this. We provision and potentially
> manage
> > large quantities of data in memory for a long period. You would lose the
> > value if you keep provisioning and releasing the memory (which a dynamic
> > resource manager is built to do).



> - I would expect using mesos to managed
> > in-memory db for adhoc processes such as machine learning tasks where
> once
> > results are generated, nodes are no longer required and can be torn down.
> > Here, can I say snappydata would be able to provide fast processing for
> > such ML tasks? e.g data forensics, fraud analysis
>

ok. Yes, assuming your ML tasks are iterative and need repeated access it
makes sense to consider snappy.


> >
> > That being said, mesos would make sense for you to manage your entire
> data
> > center (or a subset) as a farm of resources and being fully abstracted
> away
> > from knowing the nodes used for snappydata. Is this your motivation for
> > mesos?



> This is would be what I intend to use for conventional olap
> > queries. So having separate cluster of nodes for snappydata make sense
> > here, e.g. top sales by region, product sales analysis, etc


ok

>
>
>
>
> >
> > I suppose, there is nothing preventing you to launch snappy using mesos
> > with some static provisioning policy?



> This is probably my challenge in
> > spinning up snappydata nodes in a mesos cluster


We will look at supporting mesos natively at some point. Maybe, you have a
few cycles to help us get there sooner :-)


>
> >
> > When you say "speed layer" you would use snappy for both stream
> processing
> > as well as a operational in-memory db? Yes for both.
>
>

**Comment by thbeh** [comment] 2016-07-08 03:51
quick question....i don't see any guide to start pulse on 0.5.0?

**Comment by SachinJanani** [comment] 2016-07-08 06:39
@thbeh To start pulse with snappydata-0.5 cluster please follow the below steps:
1) Change locators configuration to have these parameters `-jmx-manager-start=true -jmx-manager-http-port=7075`
2) Restart the snappydata cluster and open the URL [http://localhost:7075/pulse](http://localhost:7075/pulse)
3) Provide default username and password as `admin`

Note: We are continuously improving pulse so please let me know if you see any issues

**Comment by thbeh** [comment] 2016-07-11 04:09
Question - I manage to create 2 dockers container, one locator (locator1) and one server (server1).

When I login to server1's snapp[y-shell, I have to connect client 'localhost:1527', is that correct? what's the column showing NETSERVERS?
![snappy-shell](https://cloud.githubusercontent.com/assets/7357830/16719708/c8f51922-4781-11e6-8f1f-9e490178c149.PNG)

**Comment by sumwale** [comment] 2017-04-22 18:46
Zeppelin usage has been [documented](http://snappydatainc.github.io/snappydata/howto/#how-to-use-apache-zeppelin-with-snappydata) and is tested before releases so closing. @thbeh

**Closed by sumwale** 2017-04-22 18:46 UTC
