### ISSUE TITLE
Fail to create table FK constraint via ALTER TABLE command

### ISSUE THREAD

**Issue by mp-calebs** [SnappyDataInc/snappydata#666] opened 2017-06-20 20:11 UTC
During the data server startup, I'm seeing lots of warnings as the following. 

17/06/20 15:02:22.605 CDT Pooled Waiting Message Processor 7<tid=0xdf> WARN snappystore: GfxdDDLMessage@3dfbcc0c(processorId=14853; processorType=77;posDup=false; connectionID=17179876588; statementID=25769803803; ddl={DDLConflatable [25769803803] SQLText [ALTER TABLE TBL_PRIVS ADD CONSTRAINT TBL_PRIVS_FK1 FOREIGN KEY (TBL_ID) REFERENCES TBLS (TBL_ID) ] fullTableName=SNAPPY_HIVE_METASTORE.TBL_PRIVS;defaultSchema=SNAPPY_HIVE_METASTORE;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=true;isAlterTableDropFKConstraint=false;constraintName=TBL_PRIVS_FK1;droppedFKConstraints=null;flags=0xa1;additionalFlags=0x18;skipLocalPeek=0;isHDFSPersistent=true;hdfsstoreName=null}) SQL exception in executing DDL
java.sql.SQLException(XJ001): Java exception: ': java.lang.NullPointerException'.
        at com.pivotal.gemfirexd.internal.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:124)
        at com.pivotal.gemfirexd.internal.impl.jdbc.Util.newEmbedSQLException(Util.java:110)
        at com.pivotal.gemfirexd.internal.impl.jdbc.Util.javaException(Util.java:318)
        at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:830)
        at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:656)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2999)
        at com.pivotal.gemfirexd.internal.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:112)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2564)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
        at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.processMessage(GfxdDDLMessage.java:311)
        at com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
        at com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:221)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:431)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:503)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:730)
        at com.gemstone.gemfire.distributed.internal.DistributionManager$7$1.run(DistributionManager.java:1091)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.pivotal.gemfirexd.internal.impl.sql.execute.DDLConstantAction.storeConstraintDependenciesOnPrivileges(DDLConstantAction.java:616)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.CreateConstraintConstantAction.executeConstantAction(CreateConstraintConstantAction.java:423)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.AlterTableConstantAction.executeConstantAction(AlterTableConstantAction.java:770)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:64)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:593)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2159)
        ... 13 more

But I get the same error when I try to add a FK constraint to a table with the ALTER TABLE command as below.

ALTER TABLE das.location ADD CONSTRAINT loc_store_fk FOREIGN KEY (store_id) REFERENCES das.loc_store(store_id);

This problem occurs in 0.8 as well as in 0.9. 
The server has the gemfirexd.sql-authorization=true with custom auth provider. 

gemfirexd.auth-provider=com.xxx.MPUserAuthenticator

I don't see such a problem if authorization is not enabled.

**Comment by mp-calebs** [comment] 2017-06-20 20:26
After I made the following changes, I don't see such warning or error any more. 
The first change is to get the current user info if the LanguageConnectionContext exists in GfxdDDLMessage.java

protected void processMessage(final DistributionManager dm)
      throws GemFireCheckedException {

    try {
      wrapper = GfxdConnectionHolder.getOrCreateWrapper(ddl.getCurrentSchema(),
          this.args.connId, true, getCurrentUserProperties()); // MP_CHANGE: https://github.com/SnappyDataInc/snappydata/issues/666
      final EmbedConnection conn = wrapper.getConnectionForSynchronization();
....
}

  // MP_CHANGE_BEGIN
  // ISSUE: https://github.com/SnappyDataInc/snappydata/issues/666
  protected Properties getCurrentUserProperties() {
    LanguageConnectionContext lcc = Misc.getLanguageConnectionContext();
    if(lcc == null) {
      return null;
    }
    String userName = lcc.getAuthorizationId();
    if (userName.indexOf('-') >= 0) {
      userName = "\"" + userName.toLowerCase() + "\"";
    }
    Properties props = new Properties();
    props.put("user", userName);
    return props;
  }
  // MP_CHANGE_END

**Comment by mp-calebs** [comment] 2017-06-20 20:30
The second change is to cover the case when lcc is null and the user is the internal hive user -
 SNAPPY_HIVE_METASTORE.

DDLConstantAction.java

					permDesc = statPerm.getPermissionDescriptor(lcc.getAuthorizationId(), dd);				
					if (permDesc == null) 
					{
						//No REFERENCES privilege exists for given 
						//authorizer at table or column level.
						//REFERENCES privilege has to exist at at PUBLIC level
						permDesc = statPerm.getPermissionDescriptor(Authorizer.PUBLIC_AUTHORIZATION_ID, dd);
						// MP_CHANGE: permDesc can be null
						if (permDesc != null && !(permDesc.checkOwner(lcc.getAuthorizationId())))
							dm.addDependency(dependent, permDesc, lcc.getContextManager());
					}

**Comment by ymahajan** [comment] 2017-06-20 20:36
@mp-calebs It seems like a bug to me, SNAPPY_HIVE_METASTORE is to store internal metadata and when authorization is enabled, this doesn't work. We will reproduce this and  investigate this further, evaluate your code changes as well.

**Comment by sumwale** [comment] 2017-06-20 23:03
@mp-calebs Thanks for reporting. As mentioned, right now grant/revoke etc are only supported in the "rowstore" mode i.e. no Spark features. As you have being finding, there are issues with "route-query=false" due to other reasons. We plan to enable this for the 1.0 GA release.

**Comment by sumwale** [comment] 2017-09-19 16:14
@mp-calebs Closing this issue since grant/revoke etc are available in enterprise 1.0 RC release.

**Closed by sumwale** 2017-09-19 16:14 UTC
