### ISSUE TITLE
Streaming Job is not getting stopped & Cache is not getting cleared (Spark Cache UI)

### ISSUE THREAD

**Issue by annpricksedmund** [SnappyDataInc/snappydata#1319] opened 2019-05-20 10:01 UTC
We got an issue that streaming job has running continuously even though the job got stopped.

We have started a simple job which will stream the data from external kafka source and store it into snappydata. After some time, we have manually stopped the job using `snappy-job.sh stop --job-id & snappy-job.sh stopcontext `and the job has been moved to completed job list (I can see in job server UI). However, the data was getting inserted into the table (I can see that the number of records has been increased) and it has continue more than 5 hours. After that, we stopped kafka and restarted the kafka after few hours, but still the data is getting processed and inserted into that table.

I didn’t see the job in jobserver UI with running status, Also, didn’t understand how the job is running and processing the data. Could you guys please check the scenario and let us know how to stop the streaming job (Any other way to stop the job).

Also, persisted RDD is not getting cleared from the cache (Verified through Spark Cache UI).

Please note that, we pulled latest master and working with that and facing all the above critical issues.

**Comment by vatsalmevada** [comment] 2019-05-21 10:53
Closing this issue as resolution of both the issue is already provided on slack. 

Summary: 
--
Issue: RDD cache not getting cleared after processing each batch 
Solution: Was a known issue in snappydata 1.0.2.1. With latest snappyversion it is already fixed
-- 
Issue: New jobs being spawned observed on snappydata pulse UI jobs tab
Solution: The snappyjob code was extending `SnappyStreamingJob` which created a `StreamingContext` which was possibly spawning jobs on batch interval independent from the streaming query. Extending `SnappySQLJob` instead of `SnappyStreaminJob` fixed the issue.

**Closed by vatsalmevada** 2019-05-21 10:53 UTC
