### ISSUE TITLE
Different results of nearly identical queries

### ISSUE THREAD

**Issue by swjung94** [SnappyDataInc/snappydata#962] opened 2018-02-13 01:34 UTC
Hi, I created two tables partitioned by 2 columns.

such as
create table table1 using column options (string key, string data, string ym) (partition by 'ym, key');
create table table2 using column options (string key, string data, string dt) (partition by 'dt, key');

and when I joined these two tables

query1: select * from table1 join table2 
             on (table1.ym = substr(table2.dt,1,6) and table1.key = table2.key)
query2: select * from table1 join table2 
             on (table1.key = table2.key and table1.ym = substr(table2.dt,1,6))

In this case, query1 got the correct result but query2  didn't.

Thanks.

**Comment by ymahajan** [comment] 2018-02-13 21:30
@swjung94 , the query result differs when you change the order of join predicates ? join keys in both the queries are partitioning keys also. let me reproduce this at my end, and see what's the difference in both the query plans. How many approximate rows you have inserted in these tables ? and wanted to check if this reproduces consistently?

**Comment by swjung94** [comment] 2018-02-19 02:41
Sorry, My first question is not correct. Below example is a bit different, but you can check it.
I attached my queries and results.

![image](https://user-images.githubusercontent.com/28548036/36360587-c584b5f2-1568-11e8-984a-6b03a0834343.png)
![image](https://user-images.githubusercontent.com/28548036/36360601-eb5b6104-1568-11e8-9d12-aec45fac933c.png)

![image](https://user-images.githubusercontent.com/28548036/36360543-5691c3b0-1568-11e8-9ed6-eaf620f869b1.png)
![image](https://user-images.githubusercontent.com/28548036/36360581-b95e3c6c-1568-11e8-86c7-362bc60d0441.png)

![image](https://user-images.githubusercontent.com/28548036/36360688-9a1fa790-1569-11e8-9f45-0c7e82171e5e.png)

![image](https://user-images.githubusercontent.com/28548036/36360694-b8e5c178-1569-11e8-9db4-c39094849d8b.png)

**Comment by sumwale** [comment] 2018-02-19 08:59
@swjung94 Thanks for details. Trying to reproduce the issue.

**Comment by sumwale** [comment] 2018-02-19 16:10
@swjung94 Have been able to identify the issue. Its due to EXCHANGE hash ordering being (f1, ym) in the first query for t2 rather than (ym, f1) to match the t1 table partitioning. It will happen for the specific case when query join order is different from partitioning of one of the tables while the other table being joined is partitioned differently.

For now you can avoid this by increasing the "spark.sql.autoBroadcastJoinThreshold" to higher value just before the query e.g. "set spark.sql.autoBroadcastJoinThreshold=100000000" so that broadcast join happens in the query (check GUI plan to confirm) which is safe because filter is reducing size to <200K rows (restore to 10M for other queries). However, on my laptop it has worse performance (~3s vs ~500ms). Or use the other query having same join order as partitioning.

Thanks for reporting. @rishitesh as discussed need to correct the join ordering in the plan

**Comment by sumwale** [comment] 2018-03-08 13:15
@swjung94 Being tracked in https://jira.snappydata.io/browse/SNAP-2225 so closing this (PR: https://github.com/SnappyDataInc/snappydata/pull/971). Thanks for the report.

**Closed by sumwale** 2018-03-08 13:15 UTC
