### ISSUE TITLE
Caused by: java.lang.IllegalStateException: StreamingContext has already been stopped

### ISSUE THREAD

**Issue by zhengbo0** [SnappyDataInc/snappydata#538] opened 2017-03-21 02:23 UTC
I follow  `Stream SQL through snappy-sql` step by step,there is error throw
```
错误 38000：(SQLState=38000 Severity=20000) (Server=localhost/127.0.0.1[1529] Thread=pool-3-thread-4) 求值表达式时抛出异常“com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: dserver4(501788)<v1>:51742, caused by java.lang.IllegalStateException: StreamingContext has already been stopped”。
Caused by: ServerException: Server STACK: java.sql.SQLException(38000): 求值表达式时抛出异常“com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: dserver4(501788)<v1>:51742, caused by java.lang.IllegalStateException: StreamingContext has already been stopped”。
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:808)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:753)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:282)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:332)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:274)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeOnLeadNode(SnappyActivation.java:234)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeWithResultSet(SnappyActivation.java:123)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.execute(SnappyActivation.java:86)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericActivationHolder.execute(GenericActivationHolder.java:462)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:586)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2159)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
	at io.snappydata.thrift.server.SnappyDataServiceImpl.execute(SnappyDataServiceImpl.java:1656)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1511)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1495)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at io.snappydata.thrift.server.SnappyDataServiceImpl$Processor.process(SnappyDataServiceImpl.java:197)
	at io.snappydata.thrift.server.SnappyThriftServerThreadPool$WorkerProcess.run(SnappyThriftServerThreadPool.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: dserver4(501788)<v1>:51742, caused by java.lang.IllegalStateException: StreamingContext has already been stopped
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.moveNext(GfxdQueryStreamingResultCollector.java:451)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.<init>(GfxdQueryStreamingResultCollector.java:363)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector.iterator(GfxdQueryStreamingResultCollector.java:207)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:276)
	... 20 more
Caused by: java.lang.IllegalStateException: StreamingContext has already been stopped
```
my code is here, I have tried version 0.7 and version 0.8 ，but don't lucky,it doesn't work
```
connect client 'localhost:1528';
streaming init 2secs; 
create stream table adImpressionStream (
        time_stamp timestamp,
        publisher string,
        advertiser string,
        website string,
        geo string,
        bid double,
        cookie string) using directkafka_stream options(
        rowConverter 'org.apache.spark.examples.snappydata.RowsConverter',
        kafkaParams 'metadata.broker.list->localhost:9092;auto.offset.reset->smallest',
        topics 'kafka_topic');      
streaming start;
```

**Comment by zhengbo0** [comment] 2017-03-21 03:40
I tried it again in my notebook,a new exception was found，need your help, thanks
```
snappy> streaming start;
错误 38000：(SQLState=38000 Severity=20000) (Server=localhost/127.0.0.1[1528] Thread=pool-3-thread-1) 求值表达式时抛出异常“com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 192.168.1.227(22631)<v1>:15798, caused by java.lang.IllegalArgumentException: requirement failed: No output operations registered, so nothing to execute”。
Caused by: ServerException: Server STACK: java.sql.SQLException(38000): 求值表达式时抛出异常“com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 192.168.1.227(22631)<v1>:15798, caused by java.lang.IllegalArgumentException: requirement failed: No output operations registered, so nothing to execute”。
```

**Comment by sonalsagarwal** [comment] 2017-03-21 12:51
@zhengbo0 
We could also reproduce this issue and it seems to be broken from snappy-sql shell. We are looking into the issue.
Till then can you give a try using job for streaming, you can refer TwitterPopularTagsJob.scala from the examples.

 I have also opened a JIRA to track the issue, [SNAP-1411](https://jira.snappydata.io/browse/SNAP-1411)

**Comment by zhengbo0** [comment] 2017-03-22 02:33
`extends SnappyStreamingJob` seems to work, thanks for your reply

**Comment by ymahajan** [comment] 2017-05-02 16:31
@zhengbo0, This has been fixed on master now, and should be available in next SnappyData release.

**Closed by ymahajan** 2017-05-02 16:31 UTC
